services:
  app:
    container_name: fetch_h3_data
    build: .
    env_file:
      - .env
    networks:
      - thno
    volumes:
      - clbb-modules-cache:/usr/src/app/shared

volumes:
  clbb-modules-cache:
    external: true

networks:
  thno:
    external: true