services:
  app:
    container_name: fetch_base_data
    build: .
    env_file:
      - .env
    # networks:
      # - thno
    volumes:
      # - ../../shared:/usr/src/app/shared
      - clbb-modules-cache:/usr/src/app/shared

volumes:
  clbb-modules-cache:
    external: true

# networks:
#   thno:
#     external: true