version: "3"

services:
  app:
    container_name: isocrone
    build: .
    env_file:
      - .env
    volumes:
      - tmp:/app/tmp    
    networks:
      - clbb
volumes:
  tmp:

networks:
  clbb:
    external: true
