version: "3"

services:
  app:
    container_name: am_prox_by_node_points
    build: .
    env_file:
      - .env
    volumes:
      - tmp:/app/tmp
    networks:
      - clbb

volumes:
  tmp:

networks:
  clbb:
    external: true
